### PR TITLE
fix/duplicate-turn-print

### PR DESCRIPTION
**Pull request by Segelzwerg**
If I remember correctly there was a print after the Stich that it is the first player's turn again.

### CODE REVIEW

**Review by iTitus — COMMENTED** [review]
Well we still need the player turn info after the first and second card is played.

**Comment by Segelzwerg** [comment]
> Well we still need the player turn info after the first and second card is played.
 yes you are right, I just tested if

```sh
Card HeB played. Cards currently on table: KaB(24) PiB(56) HeB(40)
It is user2's turn.        <- this one should not happen
> --
You lost the Stich. Gid good.
It is user2's turn.
```

**Comment by Segelzwerg** [comment]
I think I fixed it

```sh
Successfully played card Ka8. Cards currently on table: Ka9(19) KaD(20) Ka8(18)
> --
You lost the Stich. Gid good.
It is user2's turn.
> 
```

**Comment by iTitus** [comment]
I think you fixed this in the wrong place. The print after the stich is done is correct, but the print after the last card is played needs to go

**Comment by Segelzwerg** [comment]
> I think you fixed this in the wrong place. The print after the stich is done is correct, but the print after the last card is played needs to go

yes you are right
```sh
Card Ka7 played. Cards currently on table: KaB(24) Ka9(19) Ka7(17)
It is 1's turn.
> --
You lost the Stich. Gid good.
It is 1's turn.
```

**Pull request closed without merging**
